kind: pipeline
name: Mac Test CI
type: exec

clone:
  depth: 30

platform:
  os: darwin
  arch: amd64

steps:
- name: greeting
  commands:
  - echo Ohaio sekai good morning worldoooOoooOoo!

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*
  - refs/pull/**

node:
  server: mac